# Generated by Django 4.2 on 2023-04-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_rename_id_like_like_is_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='id_marked',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='is_marked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='like',
            name='is_like',
            field=models.BooleanField(default=False),
        ),
    ]
